//
// Generated by afu_json_mgr from /home/abelardojara/workspace_remote/intel-fpga-bbb/samples/tutorial/01_hello_world/hw/rtl/cci_hello.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "cci_hello"
`define AFU_ACCEL_UUID 128'hc6aa954a_9b91_4a37_abc1_1d9f0709dcc3
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
